CREATE TABLE ITEM (
   ID INT PRIMARY KEY,
   DESCRICAO VARCHAR(255) NOT NULL,
   PONTOS INT NOT NULL
);

INSERT INTO ITEM (ID, DESCRICAO, PONTOS) VALUES (1, 'Arma', 4);
INSERT INTO ITEM (ID, DESCRICAO, PONTOS) VALUES (2, 'Munição', 3);
INSERT INTO ITEM (ID, DESCRICAO, PONTOS) VALUES (3, 'Água', 2);
INSERT INTO ITEM (ID, DESCRICAO, PONTOS) VALUES (4, 'Comida', 1);
