CREATE TABLE REBELDE (
   ID INT PRIMARY KEY,
   NOME VARCHAR(255) NOT NULL,
   IDADE INT NOT NULL,
   GENERO VARCHAR(15) NOT NULL,
   TRAIDOR BOOLEAN DEFAULT FALSE,
   LOCALIZACAO INT NOT NULL,
   foreign key (LOCALIZACAO) references LOCALIZACAO(ID)
);

