CREATE TABLE LOCALIZACAO (
   ID INT PRIMARY KEY,
   LATITUDE DECIMAL NOT NULL,
   LONGITUDE DECIMAL NOT NULL,
   NOME VARCHAR(255) NOT NULL,
   GALAXIA VARCHAR(255) NOT NULL,
   BASE VARCHAR(255) NOT NULL
);
