CREATE TABLE REPORTE_DE_TRAICAO (
   ID INT PRIMARY KEY,
   ID_REPORTER INT NOT NULL,
   ID_REPORTADO INT NOT NULL,
   DATA_DO_REPORTE DATE NOT NULL,
   foreign key (ID_REPORTER) references Rebelde(ID),
   foreign key (ID_REPORTADO) references Rebelde(ID)
);
